### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by nryang** [chpmrc/graphene-validator#2]
First of all, I want to say thank you for writing this validator for graphene inputs. This is something that is missing from the library.

Are there plans to upload this to pypi for general use?

**Comment by elchiapp** [comment]
Hey Nathan thank you for your kind comment. I tried getting the attention of graphene's devs, to integrate this directly, but to no avail so I'll work on uploading this to pypi in the upcoming days.

**Comment by klintan** [comment]
Any news on this ? :)

**Comment by jklq** [comment]
Also wondering if there are any news on this

**Comment by elchiapp** [comment]
Wanted to wait for https://github.com/chpmrc/graphene-validator/pull/11 but I think I can make another release later. Honestly haven't made an official release because I didn't think the package was ready but apparently it's already being used in multiple projects so no point in waiting. I'll try to get to it this week.

**Comment by elchiapp** [comment]
0.0.1 is now available on Pypi: https://pypi.org/project/graphene-validator/0.0.1/
Let me know if everything looks ok, will test more in the upcoming days. 

(Leaving open to get some feedback)

**Comment by jklq** [comment]
Nice! Thank you!
